# Generated by Django 4.1.1 on 2022-09-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_orderitem_book_id_remove_orderitem_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_id_storage',
            new_name='storage_book_id',
        ),
    ]
